Added in a PoolBuilder.
fulcrumgenomics/pooled-writer pull request #1
Opened 2022-12-11 04:47 UTC by tfenne

I created a `PoolBuilder` which allows for usage like:
1. Create builder
2. Configure builder
3. Exchange writers one at a time for PooledWriters
4. Build the pool

This should be much easier to use when the writers are naturally in a single Vec or other linear structure (e.g. when they're grouped by samples and file types).

I'm tempted to remove the non-builder way of creating the pool, but thought I'd see what you guys thought first.

2022-12-11 06:12 UTC, nh13 requested changes

2022-12-11 06:12 UTC, nh13 commented on src/lib.rs
> +            compressor_tx: compressor_tx,
```suggestion
            compressor_tx,
```

2022-12-11 06:12 UTC, nh13 commented on src/lib.rs
> +    writer_rxs: Vec<Receiver<Receiver<WriterMessage>>>,
doc comments (since this is a public struct)

2022-12-11 06:12 UTC, nh13 commented on src/lib.rs
> +    pub fn with_writer_threads(mut self, n: usize) -> Self {
Looking at the naming style [here](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html) and [here](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html) for the builder pattern, as well in the [`derive_builder`](https://docs.rs/derive_builder/latest/derive_builder/) crate, it would seem that this method should be called `writer_threads`.  Thoughts?

2022-12-11 06:12 UTC, nh13 commented on src/lib.rs
> +            pool_handle: Some(handle),
I don't understand why these are optional in `Pool`

2022-12-11 06:12 UTC, nh13 commented on src/lib.rs
> +/// A struct to make building up a Pool simpler.
do you want to add an example or two along side the module-level docs?

2022-12-11 13:15 UTC, tfenne commented on src/lib.rs
> +    writer_rxs: Vec<Receiver<Receiver<WriterMessage>>>,
It's a public struct, but all the fields are private.

2022-12-11 13:48 UTC, tfenne commented on src/lib.rs
> +            pool_handle: Some(handle),
It's so that `Pool::stop_pool()` can consume the values and leave `None`s behind.

2022-12-11 14:11 UTC, tfenne commented
@nh13 Made the suggested changes and reworked a bunch of the documentation.  

Also deprecated the old `Pool::new()` _and_ reimplemented it internally using the builder so there's less redundancy.

2022-12-11 14:33 UTC, tfenne commented on src/lib.rs
> +    pub fn with_writer_threads(mut self, n: usize) -> Self {
Changed.

2022-12-12 16:27 UTC, nh13 approved these changes
Thanks for making the changes, and this will be super useful!

2022-12-12 16:28 UTC, merged